"""content locking columns and audit_log table

Revision ID: 049e6dee29c2
Revises: f65dbb4e6944
Create Date: 2026-06-12 14:05:27.703104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049e6dee29c2'
down_revision = 'f65dbb4e6944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_albums_locked_by_users'), 'users', ['locked_by'], ['id'])

    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_family_member_locked_by_users'), 'users', ['locked_by'], ['id'])

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_photos_locked_by_users'), 'users', ['locked_by'], ['id'])

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_timeline_events_locked_by_users'), 'users', ['locked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_timeline_events_locked_by_users'), type_='foreignkey')
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_photos_locked_by_users'), type_='foreignkey')
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')

    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_family_member_locked_by_users'), type_='foreignkey')
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_albums_locked_by_users'), type_='foreignkey')
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
