"""create photo_tags table

Revision ID: 2cd5bb243084
Revises: e35751324ef6
Create Date: 2026-06-12 20:39:59.985911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd5bb243084'
down_revision = 'e35751324ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_photo_tags_created_by_users')),
    sa.ForeignKeyConstraint(['member_id'], ['family_member.id'], name=op.f('fk_photo_tags_member_id_family_member')),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_tags_photo_id_photos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_tags')),
    sa.UniqueConstraint('photo_id', 'member_id', name='uq_photo_tags_photo_id_member_id')
    )
    with op.batch_alter_table('photo_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_tags_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_tags_photo_id'), ['photo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_tags_photo_id'))
        batch_op.drop_index(batch_op.f('ix_photo_tags_member_id'))

    op.drop_table('photo_tags')
    # ### end Alembic commands ###
