"""create family_plans, plan_items, plan_attachments

Revision ID: 3174667cf42b
Revises: 2cd5bb243084
Create Date: 2026-06-13 22:13:42.994041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3174667cf42b'
down_revision = '2cd5bb243084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_family_plans_created_by_users')),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name=op.f('fk_family_plans_locked_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_plans'))
    )
    op.create_table('plan_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['family_plans.id'], name=op.f('fk_plan_attachments_plan_id_family_plans')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_plan_attachments_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_attachments'))
    )
    with op.batch_alter_table('plan_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_attachments_plan_id'), ['plan_id'], unique=False)

    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_plan_items_created_by_users')),
    sa.ForeignKeyConstraint(['plan_id'], ['family_plans.id'], name=op.f('fk_plan_items_plan_id_family_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items'))
    )
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_items_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_items_plan_id'))

    op.drop_table('plan_items')
    with op.batch_alter_table('plan_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_attachments_plan_id'))

    op.drop_table('plan_attachments')
    op.drop_table('family_plans')
    # ### end Alembic commands ###
