"""extend family_member into wiki page (bio, dates, edit tracking)

Revision ID: 3553f395564d
Revises: 1b938c19cd72
Create Date: 2026-06-11 18:27:52.822338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3553f395564d'
down_revision = '1b938c19cd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('death_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_family_member_updated_by_users'), 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_family_member_created_by_users'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_family_member_created_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_family_member_updated_by_users'), type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('death_date')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
