"""create site_settings table

Revision ID: 74986b0b28df
Revises: 2153d99b1199
Create Date: 2026-06-11 18:32:43.288102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74986b0b28df'
down_revision = '2153d99b1199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_site_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
