"""initial GEDCOM-7 schema

Revision ID: 8da914c51520
Revises: 
Create Date: 2026-06-16 15:03:31.321019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da914c51520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_xref', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('living', sa.Boolean(), nullable=False),
    sa.Column('restriction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_individuals')),
    sa.UniqueConstraint('gedcom_xref', name=op.f('uq_individuals_gedcom_xref'))
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_xref', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('gedcom_xref', name=op.f('uq_repositories_gedcom_xref'))
    )
    op.create_table('site_settings',
    sa.Column('setting_key', sa.String(length=80), nullable=False),
    sa.Column('setting_value', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('setting_key', name=op.f('pk_site_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('event_tag', sa.String(length=10), nullable=False),
    sa.Column('event_value', sa.String(length=255), nullable=True),
    sa.Column('date_original', sa.String(length=100), nullable=True),
    sa.Column('date_sort', sa.String(length=20), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=30), nullable=True),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_events_place_id_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_date_sort', ['date_sort'], unique=False)
        batch_op.create_index('ix_events_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_xref', sa.String(length=20), nullable=True),
    sa.Column('partner1_id', sa.Integer(), nullable=True),
    sa.Column('partner2_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner1_id'], ['individuals.id'], name=op.f('fk_families_partner1_id_individuals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner2_id'], ['individuals.id'], name=op.f('fk_families_partner2_id_individuals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families')),
    sa.UniqueConstraint('gedcom_xref', name=op.f('uq_families_gedcom_xref'))
    )
    op.create_table('media_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_xref', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_objects_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_objects')),
    sa.UniqueConstraint('gedcom_xref', name=op.f('uq_media_objects_gedcom_xref'))
    )
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('name_type', sa.String(length=20), nullable=False),
    sa.Column('name_prefix', sa.String(length=50), nullable=True),
    sa.Column('given', sa.String(length=150), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('surname_prefix', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=150), nullable=True),
    sa.Column('name_suffix', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_names_individual_id_individuals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_names'))
    )
    with op.batch_alter_table('names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_names_individual_id'), ['individual_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_xref', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_notes_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes')),
    sa.UniqueConstraint('gedcom_xref', name=op.f('uq_notes_gedcom_xref'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_xref', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publication', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_sources_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('gedcom_xref', name=op.f('uq_sources_gedcom_xref'))
    )
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_citations_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index('ix_citations_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('family_children',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('pedigree_type', sa.String(length=20), nullable=False),
    sa.Column('child_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['individuals.id'], name=op.f('fk_family_children_child_id_individuals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_children_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'child_id', name=op.f('pk_family_children'))
    )
    op.create_table('media_links',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_objects.id'], name=op.f('fk_media_links_media_id_media_objects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'subject_type', 'subject_id', name=op.f('pk_media_links'))
    )
    with op.batch_alter_table('media_links', schema=None) as batch_op:
        batch_op.create_index('ix_media_links_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('note_links',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_links_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'subject_type', 'subject_id', name=op.f('pk_note_links'))
    )
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.create_index('ix_note_links_subject', ['subject_type', 'subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.drop_index('ix_note_links_subject')

    op.drop_table('note_links')
    with op.batch_alter_table('media_links', schema=None) as batch_op:
        batch_op.drop_index('ix_media_links_subject')

    op.drop_table('media_links')
    op.drop_table('family_children')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index('ix_citations_subject')

    op.drop_table('citations')
    op.drop_table('sources')
    op.drop_table('notes')
    with op.batch_alter_table('names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_names_individual_id'))

    op.drop_table('names')
    op.drop_table('media_objects')
    op.drop_table('families')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_subject')
        batch_op.drop_index('ix_events_date_sort')

    op.drop_table('events')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('site_settings')
    op.drop_table('repositories')
    op.drop_table('places')
    op.drop_table('individuals')
    # ### end Alembic commands ###
