"""create wiki_revisions table

Revision ID: f65dbb4e6944
Revises: 74986b0b28df
Create Date: 2026-06-12 13:16:50.791331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65dbb4e6944'
down_revision = '74986b0b28df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), server_default='', nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name=op.f('fk_wiki_revisions_edited_by_users')),
    sa.ForeignKeyConstraint(['member_id'], ['family_member.id'], name=op.f('fk_wiki_revisions_member_id_family_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_revisions'))
    )
    with op.batch_alter_table('wiki_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_revisions_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###

    # DATA MIGRATION (hand-written): wiki pages that exist BEFORE this
    # feature ships get a "version 1" snapshot of their current state, so
    # no page starts with an empty history. This is the other half of what
    # migrations are for — not just changing the shape of tables, but
    # carrying the data across the change. Plain portable SQL (runs the
    # same on SQLite today and MySQL in v2).
    op.execute("""
        INSERT INTO wiki_revisions
            (member_id, name, location, bio, birth_date, death_date,
             edited_by, created_at)
        SELECT id, name, location, bio, birth_date, death_date,
               updated_by, CURRENT_TIMESTAMP
        FROM family_member
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_revisions_member_id'))

    op.drop_table('wiki_revisions')
    # ### end Alembic commands ###
